backend:
  name: git-gateway
  branch: main  # Główna gałąź repozytorium

media_folder: "images/uploads" # Folder na zdjęcia

collections:
  - name: "strona-glowna"
    label: "Strona Główna"
    files:
      - name: "hero"
        label: "Sekcja Hero"
        file: "content/home.json"
        fields:
          - { label: "Nagłówek", name: "title", widget: "string" }
          - { label: "Opis", name: "description", widget: "text" }
          - { label: "Tło", name: "background", widget: "image" }
