backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "text" }
      - { label: "Obraz", name: "image", widget: "image" }
      - { label: "Link do projektu", name: "url", widget: "string" }
