backend:
  name: git-gateway
  branch: main  # lub master, w zależności od nazwy Twojej głównej gałęzi

media_folder: "images/uploads"  # Folder do przechowywania zdjęć

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"  # Folder, gdzie będą zapisane projekty
    create: true           # Możliwość tworzenia nowych plików
    slug: "{{slug}}"       # Tworzenie URL z tytułów
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "text" }
      - { label: "Obraz", name: "image", widget: "image" }
      - { label: "Link do projektu", name: "url", widget: "string" }
